[package]
name = "kerosene_macros"
version = "0.1.0"
edition.workspace = true
rust_version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"
